name: Sync to Azure Repos

trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: SyncToAzureRepos
  steps:
  - script: |
      echo "Syncing to Azure Repos"
      git config user.email "guillermo.santos1@alu.uclm.es"
      git config user.name "GuillermoSantosMolero"
      git remote add azure-repos https://PAT_AZURE_REPOS@dev.azure.com/GuillermoSantos1/ISO2023E2/_git/ISO2023E2
      git push azure-repos HEAD:refs/heads/main
    env:
      PAT_AZURE_REPOS: $PAT_AZURE_REPOS
    displayName: 'Push to Azure Repos'