# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Sync to Azure Repos

trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git config user.email "tu@email.com" 
    git config user.name "TuNombre" 
    git remote add azure-repos https://GuillermoSantos1@dev.azure.com/GuillermoSantos1/ISO2023E2/_git/ISO2023E2
    git push azure-repos HEAD:refs/heads/main
  displayName: 'Push to Azure Repos'
