name: Sync to Azure Repos

trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: SyncToAzureRepos
  steps:
  - script: |
      echo "Syncing to Azure Repos"
      git config user.email "guillermo.santos1@alu.uclm.es"
      git config user.name "GuillermoSantosMolero"
      export AZURE_REPOS_PAT=${{ secrets.AZURE_REPOS_PAT }}
      git remote add azure-repos https://$AZURE_REPOS_PAT@dev.azure.com/GuillermoSantos1/ISO2023E2/_git/ISO2023E2
      git push azure-repos HEAD:refs/heads/main
    displayName: 'Push to Azure Repos'