# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Sync to Azure Repos

trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git config user.email "guillermo.santos1@alu.uclm.es" 
    git config user.name "GuillermoSantosMolero" 
    git remote add azure-repos https://PAT_AZURE_REPOS@dev.azure.com/GuillermoSantos1/ISO2023E2/_git/ISO2023E2
    git push azure-repos HEAD:refs/heads/main
  displayName: 'Push to Azure Repos'
