name: Sync to Azure Repos

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to Azure Repos
      run: |
        git config --global user.email "guillermo.santos1@alu.uclm.es"
        git config --global user.name "GuillermoSantosMolero"
        git remote add azure-repos https://GuillermoSantos1:$PAT_AZURE_REPOS@dev.azure.com/GuillermoSantos1/ISO2023E2/_git/ISO_E02_FRONT
        git push azure-repos HEAD:refs/heads/main
      env:
        PAT_AZURE_REPOS: ${{ secrets.AZURE_REPOS_PAT }}
